Adding items
TalShperling/BarterIL pull request #12
Opened 2021-04-17 20:14 UTC by TalShperling

2021-04-17 20:15 UTC, TalShperling commented
![image](https://user-images.githubusercontent.com/24584679/115125721-bbf0c880-9fd2-11eb-9db9-338610d4a74a.png)

2021-04-18 18:03 UTC, Ozzorany requested changes

2021-04-18 18:03 UTC, Ozzorany commented on src/app/components/modal/modal.component.html
> +    <h4 class="modal-title w-100" id="myModalLabel">{{options.heading}}</h4>
why do you need the id myModalLabel? remove if no need

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/edit-item-modal/edit-item-modal.component.ts
> +      idForm: new FormControl(null, [Validators.required]),
consider removing the id field from being displayed.

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item-list/item-list.component.ts
> +                  alert("item deleted successfully!");
- [x] use the alert service I've created

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item-list/item-list.component.ts
> +    alert("Viewing item");
use alerts service
- [ ] same here

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item-list/item-list.component.ts
> +          console.log(savedItem);
remove console.log

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item-list/item-list.component.ts
> +  editItem(itemId: string) {
add return type to method

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item/item.component.html
> +    <div style="padding: 10px">
use mdb classes (p-2, p-3 ...)

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item/item.component.ts
> +  constructor() { }
\n

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/components/item/item.component.ts
> +  deleteItem() {
return types to those methods

2021-04-18 18:03 UTC, Ozzorany commented on src/app/items/services/items.service.ts
> +  providedIn: 'root'
remove providedIn root, and provide this service in the providers section in the relevant , module

- [ ] remove

2021-04-18 18:06 UTC, TalShperling commented on src/app/items/components/edit-item-modal/edit-item-modal.component.ts
> +      idForm: new FormControl(null, [Validators.required]),
It's disabled, I find it good since we want to enable navigation to item's page using this ID

2021-04-18 19:11 UTC, LiorVais requested changes

2021-04-18 19:11 UTC, ghost commented on src/app/items/components/item-list/item-list.component.ts
> +      this.items = itemList
use items observable with ` | async` in the html instead of subscribing

2021-04-18 19:11 UTC, ghost commented on src/app/items/components/item-list/item-list.component.ts
> +  public items: Item[] = [];
remove public
remove default value
change type to Observable<Item[]>

2021-04-18 19:11 UTC, ghost commented on src/app/items/components/item-list/item-list.component.ts
> +    const modalOptions = {
change to `const modalOptions: ModalOptions` and remove `as ModalOptions` in the end

2021-04-18 19:11 UTC, ghost commented on src/app/items/components/item/item.component.ts
> +  @Output() onDeleteItem = new EventEmitter<string>();
initiate inside onInit

2021-04-18 19:11 UTC, ghost commented on src/entities/modal.model.ts
> +    actions: {actionName:MODAL_ACTIONS, callback: ()=>{}, color: string}[];
change callback type to ()=>void

2021-04-18 19:11 UTC, ghost commented on src/entities/modal.model.ts
> +    heading: string;
rename heading to header

2021-04-18 19:11 UTC, ghost commented on src/entities/modal.model.ts
> +    component: any;
remove component if not used

2021-04-18 19:11 UTC, ghost commented on src/entities/modal.model.ts
> +export enum MODAL_ACTIONS {
enum should be in PascalCase

2021-04-18 19:11 UTC, LiorVais commented on src/app/items/components/item/item.component.ts
> +
consider emitting the item itself and then you will not need to find by id later

2021-04-22 17:01 UTC, TalShperling commented on src/app/items/components/item-list/item-list.component.ts
> +    const modalOptions = {
the object as a whole is not ModalOptions but only part of it is.

2021-04-23 10:54 UTC, Ozzorany approved these changes

2021-04-23 16:58 UTC, merged