Feature/front of add item + organizing project
TalShperling/BarterIL pull request #14
Opened 2021-04-25 22:17 UTC by yarivg

![image](https://user-images.githubusercontent.com/12229790/116011295-ef63d080-a62c-11eb-8ee5-5df845be47d4.png)

רק התחלה.. פשוט נגעתי בהרבה קבצים אז חשוב שייכנס רק חלק ראשון של צד לקוח נאיבי עם כלל השינויים הקומסטיים בקוד

2021-04-26 16:54 UTC, Ozzorany commented
@yarivg  
למה המסך הראשי נראה ככה? כל הכרטיסיות, עשיתי merge מ develop לשינויים שלי?

2021-04-26 17:00 UTC, Ozzorany requested changes

2021-04-26 17:00 UTC, Ozzorany commented on src/app/components/add-item-float-button/add-item-float-button.component.scss
> +.add-item-sticky-button {
make the + button circle and not square

2021-04-26 17:00 UTC, Ozzorany commented on src/app/components/add-item-float-button/add-item-float-button.component.ts
> +  openAddItemModal() {
return type

- [ ] return type

2021-04-26 17:00 UTC, Ozzorany commented on src/app/components/add-item-float-button/add-item-float-button.component.ts
> +          console.log('Hey zot-ani');
remove (:

- [x] remove

2021-04-26 21:35 UTC, yarivg commented on src/app/components/add-item-float-button/add-item-float-button.component.ts
> +          console.log('Hey zot-ani');
עוז אני מעיף את זה בPR המשך.. פשוט זה הוסט להיות PR של סידור של תיקיות של קומפוננטות.. נהיו כמה תיקיות COMPONENTS בפרויקט איכשהו

2021-04-26 21:35 UTC, yarivg commented on src/app/components/add-item-float-button/add-item-float-button.component.ts
> +          console.log('Hey zot-ani');
אני פשוט מממש שם משהו במקום חח

2021-04-26 21:39 UTC, yarivg commented on src/app/components/add-item-float-button/add-item-float-button.component.scss
> +.add-item-sticky-button {
done

2021-04-28 15:11 UTC, Ozzorany approved these changes

2021-04-28 15:11 UTC, merged