adding image-carousel for more then one image.
TalShperling/BarterIL pull request #20
Opened 2021-05-10 21:15 UTC by TalShperling

Connecting user to item by ownerId prop in item

2021-05-10 21:16 UTC, TalShperling commented
![image](https://user-images.githubusercontent.com/24584679/117725627-0e965c80-b1ee-11eb-852b-eb8de9dc3aa7.png)

2021-05-11 16:57 UTC, Ozzorany commented
@TalShperling 
1. can you add more than 1 image when you upload picture to the image? Or it's just extra thing for now?
2. fix conflicts

- [ ] conflicts

2021-05-11 20:18 UTC, ghost requested changes

2021-05-11 20:18 UTC, ghost commented on src/app/items/components/item-list/item-list.component.html
> +        <app-item class="card-deck mt-4" *ngFor="let item of itemsList" [item]="item" [currentUser]="currentUser$ | async"
move the pipe into an ngif to subscribe only once

2021-05-11 20:18 UTC, ghost commented on src/app/items/components/edit-item-modal/edit-item-modal.component.ts
> +        ownerId: this.currentUser.id,
this will be null if the subscription above delays for any reason.. It is better to find another solution
maybe pass the currentUser into the modal as parameter?

2021-05-11 21:49 UTC, TalShperling commented on src/app/items/components/edit-item-modal/edit-item-modal.component.ts
> +        ownerId: this.currentUser.id,
transferred it to the effect instead of providing it down in the component tree and then upwards again

2021-05-12 15:37 UTC, LiorVais requested changes

2021-05-12 15:37 UTC, LiorVais commented on src/app/items/components/edit-item-modal/edit-item-modal.component.ts
> +  currentUser: User;
remove if not used
1. currentUser
2. extends ObservableListener

2021-05-12 15:37 UTC, LiorVais commented on src/app/items/effects/items.effects.ts
> +    withLatestFrom(this.store$.select(getUser)),
it is better to use `this.store.pipe(select(getUser))`
just newer syntax while the old one will be deprecated

2021-05-12 19:18 UTC, merged